### ISSUE TITLE
Defer to merge_chunks in special cases of rechunk

### ISSUE THREAD

**Issue by TomNicholas** [cubed-dev/cubed#282]
#221 introduced `merge_chunks`, a special-case of `rechunk` that can be implemented using `blockwise`. I noticed that whilst `reduction` calls `merge_chunks` directly, inside `ops.rechunk` the [primitive rechunk is always called](https://github.com/tomwhite/cubed/blob/93ad984e7b0445164ab11b3c3f3a3b7db6c3bc97/cubed/core/ops.py#L631C11-L631C11). Shouldn't it be possible for `ops.rechunk` to check if the user is asking them to perform that special case, and internally dispatch to `merge_chunks`?

This also makes me wonder whether there are any other special cases of `rechunk` that could be written using `blockwise`.

**Comment by tomwhite** [comment]
This should be possible, but I'm not sure how much this occurs in practice. The only calls to `rechunk` in Cubed are in `reshape` and `from_array` (for some cases).

**Comment by TomNicholas** [comment]
It will also happen if an xarray user calls `.rechunk`, because it [dispatches to cubed's `rechunk` method](https://github.com/pydata/xarray/blob/92c8b33eb464b09d6f8277265b16cae039ab57ee/xarray/core/parallelcompat.py#L313).

I agree it's not a very common case (though I expect it to come up in the [full pangeo vorticity example](https://github.com/pangeo-data/distributed-array-examples/issues/1#issuecomment-1534972901) where we pad then rechunk to merge the padded values back in).

**Comment by dcherian** [comment]
>   there are any other special cases of rechunk that could be written using blockwise.
> It will also happen if an xarray user calls .chunk on an already-chunked array

This is very confusing to me. 

Isn't a `rechunk` without a on-disk intermediate not "blockwise" by definition (you are communicating across chunks)? I thought the optimization was effectively optimizing chunking when reading from an intermediate store by looking at the chunks needed for the succeeding operation. But perhaps I'm misunderstanding something.

**Comment by TomNicholas** [comment]
`merge_chunks` is implemented using [`map_direct`](https://tom-e-white.com/cubed/operations.html#map-direct), which 

> works by creating an empty array that has the same shape and chunk structure as the output, and calling map_blocks on this empty array, passing in the input arrays as side inputs to the function, which may access them in whatever way is needed.

That might resolve it for you @dcherian ?

Alternatively, the way I have been thinking about this `merge_chunks` operation is as just one-half of what rechunker does. In Tom A's [original suggestion that led for rechunker](https://discourse.pangeo.io/t/best-practices-to-go-from-1000s-of-netcdf-files-to-analyses-on-a-hpc-cluster/588/12?u=tomnicholas), he breaks general rechunking into a _split pass_ and a _merge pass_. If you can accomplish the specific rechunk only doing the merge pass you don't need the intermediate store.
