### ISSUE TITLE
Lithops version mismatch

### ISSUE THREAD

**Issue by TomNicholas** [cubed-dev/cubed#324]
I tried to re-run the quadratic means example with recent improvements to Cubed but got stuck on a Lithops version mismatch error

```
Exception: Lithops version mismatch. Host version 2.9.0 - Runtime version: 3.0.1
```

I can't seem to get these numbers to change - re-installing the local version of lithops via pip, or changing the `requirements.txt` file that should build the runtime environment doesn't seem to change either of them. I'm probably doing something dumb with my local env but it's annoying.

**Comment by abourramouss** [comment]
> I tried to re-run the quadratic means example with recent improvements to Cubed but got stuck on a Lithops version mismatch error
> 
> ```
> Exception: Lithops version mismatch. Host version 2.9.0 - Runtime version: 3.0.1
> ```
> 
> I can't seem to get these numbers to change - re-installing the local version of lithops via pip, or changing the `requirements.txt` file that should build the runtime environment doesn't seem to change either of them. I'm probably doing something dumb with my local env but it's annoying.

Usually after bulding the runtime with some python version or lithops version, i.e 2.9.0, you'll have to deploy the function first.

**Comment by tomwhite** [comment]
Thanks @abourramouss.

I got it working by using the instructions at https://github.com/tomwhite/cubed/tree/main/examples/lithops/gcf, but using Python 3.9 rather than 3.8 (as that's the minimum for Cubed now):

```
conda create --name cubed-lithops-gcf-examples -y python=3.9
```

I also explicitly deleted the runtime to be sure that it was created from scratch

```
lithops runtime delete -b gcp_functions -d cubed-runtime
```

**Comment by tomwhite** [comment]
Closing this as it's quite old - please reopen if it's still a problem
