### ISSUE TITLE
Allow non-string specification of stores

### ISSUE THREAD

**Issue by rabernat** [cubed-dev/cubed#390]
For compatibility with Arraylake, we would want to expand this type

https://github.com/cubed-dev/cubed/blob/738b70d5578cf9dd68bb36fa813d96ffd0dd7302/cubed/types.py#L21

to allow passing a Zarr Store object (rather than a string), plus optionally a group argument.

We would probably like to call [to_zarr](https://cubed-dev.github.io/cubed/generated/cubed.to_zarr.html#cubed-to-zarr) like this

```python
from arraylake import Client
client = Client()
repo = client.get_repo("earthmover/foo")

to_zarr(x, store=repo.store, group="sub/group")
```

The `repo.store` object is serializable.

**Comment by tomwhite** [comment]
Thanks for opening the issue @rabernat.

> we would want to expand this type

I'm not sure what the best type signature is here, so probably `Any`?

I've opened #391 to allow a group argument (in `from_zarr` too), which should support your use case. I've called it `path` as that is what Zarr seems to call it, but I notice Dask calls it `component`. Any thoughts about naming?

**Comment by rabernat** [comment]
> I'm not sure what the best type signature is here, so probably `Any`?

It would be one of the base types from Zarr, e.g. https://github.com/zarr-developers/zarr-python/blob/f80f697c2612cf41c5bdb158a602c1ae8a737e70/zarr/_storage/store.py#L164

(However, these are going to evolve soon with the Zarr V3 refactor.)

> I've called it `path` as that is what Zarr seems to call it, but I notice Dask calls it `component`

To make it even more fun, Xarray calls it `group`! 🙃 `path` is fine.
