### ISSUE TITLE
Removing `numpy.array_api` import

### ISSUE THREAD

**Issue by rgommers** [cubed-dev/cubed#407]
Hi, I noticed through code search that there are a few comments in this repo that reference `numpy.array_api` and (more importantly) one import:

https://github.com/cubed-dev/cubed/blob/76ea07e6301c53202b990442677e1c82da5e2a3a/cubed/array_api/data_type_functions.py#L4

I wanted to give you a heads up that in NumPy 2.0 that import will break. Because we'll have support for the array API standard in the main `numpy` namespace, the `numpy.array_api` submodule is being removed (see https://github.com/numpy/numpy/pull/25911).

For testing purposes, https://github.com/data-apis/array-api-strict can be used. The `Dtype` type annotation you're using is probably best vendored: https://github.com/numpy/numpy/blob/maintenance/1.26.x/numpy/array_api/_typing.py#L55-L66

**Comment by tomwhite** [comment]
Thanks for the heads up @rgommers!

That code and all the other places with comments referencing `numpy.array_api` are all concerned with dtype functions. Now that we are using Array API compliant backend array libraries (see https://github.com/cubed-dev/cubed/blob/main/cubed/backend_array_api.py) we should delegate these functions to the backend library.
