### ISSUE TITLE
outdated examples: cubed.Spec's `max_mem`  deprecated in favour of `allowed_mem`

### ISSUE THREAD

**Issue by wietzesuijker** [cubed-dev/cubed#493]
For a cubed.Spec, `max_mem` seems to be deprecated in favour of `allowed_mem`.
Running through the examples, I got a TypeError: __init__() got an unexpected keyword argument 'max_mem'
There are several places throughout the repo where this issue is present.

To reproduce:  
e.g. `spec = cubed.Spec(work_dir="tmp", max_mem=100_000)`.

To fix: 
search the repo for `max_mem` and e.g. replace `spec = cubed.Spec(work_dir="tmp", max_mem=100_000)` with `spec = cubed.Spec(work_dir="tmp", allowed_mem="100MB")`.

**Comment by tomwhite** [comment]
@wietzesuijker thanks for reporting the bug! FYI I'm away for most of this week so may be a bit slower than usual in looking at your fixes.

**Comment by tomwhite** [comment]
Fixed in #525
