### ISSUE TITLE
`HistoryCallback()` in .compute [cubed / cubed-xarray]

### ISSUE THREAD

**Issue by norlandrhagen** [cubed-dev/cubed#543]
Thanks for the new diagnostics docs @tomwhite! 

Trying to get my head around using `HistoricalCallback()` in .compute(). One example that uses it seems to be in [examples/add-random.py](https://github.com/cubed-dev/cubed/blob/bdf6dba80ecbb40efcd28c2132bce4a49fcbdc73/examples/add-random.py#L20).  Should I expect to see any output when adding `HistoryCallback()` to the callbacks in `.compute` or is this the wrong usecase?

```python 
from cubed import Spec
import xarray as xr 
from cubed.diagnostics.history import HistoryCallback

spec = Spec(work_dir='tmp', allowed_mem='2GB')
hist = HistoryCallback()

ds = xr.tutorial.open_dataset('air_temperature', chunked_array_type='cubed',
     from_array_kwargs={'spec': spec},chunks={})

rds = ds.chunk({'time':1}, chunked_array_type="cubed")

rds.compute(callbacks=[hist])
```

**Comment by TomNicholas** [comment]
Doesn't `HistoryCallback` save a bunch of extra csv files into the `tmp` directory? (Or maybe just the local directory? Pretty sure that's what it did back when I wrote the blog post https://xarray.dev/blog/cubed-xarray

**Comment by tomwhite** [comment]
It will save some CSV files in a `history/compute-{id}` directory. For example:

```shell
> ls history/compute-20240807T141305.118660                      
events.csv   plan.csv     stats.csv    timeline.svg
```

The `timeline.svg` file is created by the `TimelineVisualizationCallback`. These files are referred to in https://github.com/cubed-dev/cubed/tree/main/examples#examples-1, but I think the documentation needs to be expanded.

**Comment by norlandrhagen** [comment]
Oh good to know! I can create a small PR to add this to the docs if that's helpful.

**Comment by tomwhite** [comment]
> Oh good to know! I can create a small PR to add this to the docs if that's helpful.

That would be great, thanks @norlandrhagen!

**Comment by norlandrhagen** [comment]
https://github.com/cubed-dev/cubed/issues/538
