### ISSUE TITLE
Support Xarray Datasets and DataArrays in `cubed.visualize`

### ISSUE THREAD

**Issue by tomwhite** [cubed-dev/cubed#553]
I don't think there's currently a way of visualizing datasets in a single diagram, so this would be very handy.

**Comment by tomwhite** [comment]
Current workaround:

```python
cubed.visualize(*(ds[var].data for var in ds.data_vars.keys()))
```

**Comment by TomNicholas** [comment]
Maybe just define an Xarray accessor im cubed-xarray so that you can do ds.cubed.visualise?

https://docs.xarray.dev/en/stable/internals/extending-xarray.html

**Comment by tomwhite** [comment]
> Maybe just define an Xarray accessor in cubed-xarray so that you can do ds.cubed.visualise?
> 
> https://docs.xarray.dev/en/stable/internals/extending-xarray.html

Thanks for the suggestion @TomNicholas - I didn't know about this extension point! I have implemented it in https://github.com/cubed-dev/cubed-xarray/pull/22 and it has been working well for me.
