### ISSUE TITLE
Changes to rechunker executors

### ISSUE THREAD

**Issue by tomwhite** [cubed-dev/cubed#82]
There are some changes in cubed to the executors that derive from rechunker. It would be worth discussing how to share the code for these.

[`BeamPipelineExecutor`](https://github.com/tomwhite/cubed/blob/a131c1b8168915355c222ccd16ec4332e01e4803/cubed/runtime/executors/beam.py#L83-L126) and [`LithopsPipelineExecutor`](https://github.com/tomwhite/cubed/blob/a131c1b8168915355c222ccd16ec4332e01e4803/cubed/runtime/executors/lithops.py#L25-L51) are new and might benefit from living in rechunker. There are changes in [`pipeline.py`](https://github.com/tomwhite/cubed/blob/a131c1b8168915355c222ccd16ec4332e01e4803/cubed/runtime/pipeline.py) that are needed for these executors to work properly.

Cubed no longer uses `PipelineExecutor`s however, since we have a new [`DagExecutor`](https://github.com/tomwhite/cubed/blob/a131c1b8168915355c222ccd16ec4332e01e4803/cubed/runtime/types.py#L6-L8) that is more general. Not sure if this is useful more widely yet.

**Comment by TomNicholas** [comment]
Is there anything rechunker can do that cubed can't?

I think if not then we should just encourage people to use cubed as a replacement for rechunker, with a dedicated example that makes this correspondence explicit (e.g. #520).
